/**
 * Generates the data-preserving migration that merges per-level MINEDU school
 * rows into one row per real school and introduces the per-school question bank.
 *
 * Run with:  pnpm db:school-merge-sql [output-path] [--force]
 *
 * The default output is an ALREADY APPLIED migration: the script refuses to
 * overwrite an existing file unless `--force` is passed (see
 * `migration-write-guard.ts`). Schools in `EXCLUDED_INSTITUTION_KEYS` are no
 * longer in the data file, so a regenerated file would differ from the applied one.
 *
 * The `codMod -> institutionKey` mapping is taken from the committed
 * `prisma/data/schools.generated.ts` (regenerate it first with
 * `pnpm db:parse-schools` if the CSV changed). The output is a plain SQL file
 * applied by `prisma migrate deploy`; it is correct on an empty database
 * (fresh deploy, before the seed) and on a populated one.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { SCHOOLS } from "../data/schools.generated.js";
import { resolveMigrationWrite } from "./migration-write-guard.js";

const DEFAULT_OUT =
  "prisma/migrations/20260913120000_merge_schools_by_institution/migration.sql";

const sqlString = (value: string) => `'${value.replace(/'/g, "''")}'`;

function buildMappingValues(): string {
  const pairs = SCHOOLS.flatMap((school) =>
    school.codMods.map((codMod) => [codMod, school.institutionKey] as const),
  ).sort((a, b) => a[0].localeCompare(b[0]));

  const seen = new Set<string>();
  for (const [codMod] of pairs) {
    if (seen.has(codMod)) throw new Error(`codMod ${codMod} mapped twice`);
    seen.add(codMod);
  }

  return pairs
    .map(([codMod, key]) => `(${sqlString(codMod)},${sqlString(key)})`)
    .join(",\n");
}

function buildSql(): string {
  return `-- Merge MINEDU per-level school rows into ONE row per real school and add
-- the per-school question bank (Question.schoolId).
--
-- GENERATED by prisma/scripts/generate-school-merge-sql.ts — regenerate instead
-- of editing by hand. IRREVERSIBLE: take a database backup before deploying.
--
-- Order matters:
--   1. Question.schoolId is added and backfilled from the author's school BEFORE
--      the merge, so the repoint step below also covers questions.
--   2. School rows get their institutionKey (embedded mapping; unmapped rows
--      fall back to 'MOD-' || codMod), levels/codMods are aggregated onto the
--      canonical row (lowest id per key), FKs are repointed, duplicates deleted.
--   3. Constraints are tightened and the per-service columns are dropped.
--
-- Prisma 7 does not wrap PostgreSQL migrations in a transaction, so the whole
-- migration is wrapped explicitly: a failure leaves the database untouched.

BEGIN;

-- 1. Per-school question bank ------------------------------------------------
ALTER TABLE "Question" ADD COLUMN "schoolId" INTEGER;

UPDATE "Question" AS q
SET "schoolId" = u."schoolId"
FROM "User" AS u
WHERE q."teacherId" = u."id"
  AND q."origin" <> 'fallback_bank'
  AND u."schoolId" IS NOT NULL;

-- 2. School merge --------------------------------------------------------------
ALTER TABLE "School"
ADD COLUMN "institutionKey" VARCHAR(150),
ADD COLUMN "levels" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "codMods" TEXT[] DEFAULT ARRAY[]::TEXT[];

CREATE TEMP TABLE "_school_merge_map" (
  "codMod" VARCHAR(20) PRIMARY KEY,
  "institutionKey" VARCHAR(150) NOT NULL
);

INSERT INTO "_school_merge_map" ("codMod", "institutionKey") VALUES
${buildMappingValues()};

UPDATE "School" AS s
SET "institutionKey" = m."institutionKey"
FROM "_school_merge_map" AS m
WHERE m."codMod" = s."codMod";

UPDATE "School"
SET "institutionKey" = 'MOD-' || "codMod"
WHERE "institutionKey" IS NULL;

CREATE TEMP TABLE "_school_groups" AS
SELECT
  "institutionKey",
  MIN("id") AS "canonicalId",
  COALESCE(
    array_agg(DISTINCT "level" ORDER BY "level") FILTER (WHERE "level" <> ''),
    ARRAY[]::TEXT[]
  ) AS "levels",
  array_agg(DISTINCT "codMod" ORDER BY "codMod") AS "codMods"
FROM "School"
GROUP BY "institutionKey";

UPDATE "School" AS s
SET "levels" = g."levels",
    "codMods" = g."codMods"
FROM "_school_groups" AS g
WHERE s."id" = g."canonicalId";

CREATE TEMP TABLE "_school_repoint" AS
SELECT s."id" AS "oldId", g."canonicalId" AS "newId"
FROM "School" AS s
JOIN "_school_groups" AS g ON g."institutionKey" = s."institutionKey"
WHERE s."id" <> g."canonicalId";

UPDATE "User" AS u
SET "schoolId" = r."newId"
FROM "_school_repoint" AS r
WHERE u."schoolId" = r."oldId";

UPDATE "Question" AS q
SET "schoolId" = r."newId"
FROM "_school_repoint" AS r
WHERE q."schoolId" = r."oldId";

DELETE FROM "School" AS s
USING "_school_repoint" AS r
WHERE s."id" = r."oldId";

DROP TABLE "_school_repoint";
DROP TABLE "_school_groups";
DROP TABLE "_school_merge_map";

-- 3. Constraints ----------------------------------------------------------------
ALTER TABLE "School" ALTER COLUMN "institutionKey" SET NOT NULL;

DROP INDEX "School_codMod_key";

ALTER TABLE "School"
DROP COLUMN "codMod",
DROP COLUMN "level";

CREATE UNIQUE INDEX "School_institutionKey_key" ON "School"("institutionKey");

CREATE INDEX "School_cenEdu_idx" ON "School"("cenEdu");

CREATE INDEX "Question_schoolId_validationStatus_origin_vakStyle_idx" ON "Question"("schoolId", "validationStatus", "origin", "vakStyle");

ALTER TABLE "Question" ADD CONSTRAINT "Question_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT;
`;
}

function main() {
  const decision = resolveMigrationWrite(process.argv.slice(2), DEFAULT_OUT, (path) =>
    existsSync(resolve(path)),
  );
  if (!decision.ok) {
    console.error(decision.message);
    process.exit(1);
  }
  const outPath = resolve(decision.outPath);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, buildSql(), "utf8");
  console.log(`Wrote ${outPath} (${SCHOOLS.length} schools).`);
}

main();
