/**
 * Offline parser — converts `prisma/data/schools.csv` (MINEDU padron web) into
 * the committed TS module `prisma/data/schools.generated.ts`. The seed imports
 * the generated module so the CSV is NOT required in production.
 *
 * Run with:  pnpm db:parse-schools
 *
 * Reads the columns CODINST, COD_MOD, CODLOCAL, CEN_EDU, D_NIV_MOD, DIR_CEN,
 * D_DIST and RZSOCIAL, then merges the per-level services of the same school
 * into ONE school (see `school-grouping.ts` for the grouping rules).
 *
 * The generated module holds one school per line, including its `codMods`,
 * which is also the full `codMod -> institutionKey` mapping used by
 * `generate-school-merge-sql.ts` for the data-preserving migration.
 *
 * Notes
 * - The source CSV may start with a blank line; blank lines are ignored.
 * - Minimal RFC-4180 row parser handles optional quoted fields and embedded commas.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { groupSchoolServices, SchoolServiceRow } from "./school-grouping.js";

const CSV_PATH = resolve("prisma/data/schools.csv");
const OUT_PATH = resolve("prisma/data/schools.generated.ts");

const WANTED = [
  "CODINST",
  "COD_MOD",
  "CODLOCAL",
  "CEN_EDU",
  "D_NIV_MOD",
  "DIR_CEN",
  "D_DIST",
  "RZSOCIAL",
] as const;

type WantedColumn = (typeof WANTED)[number];

/** Minimal RFC-4180 row splitter. Handles quoted fields + escaped quotes. */
function splitRow(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (inQuotes) {
      if (c === '"') {
        if (line[i + 1] === '"') {
          cur += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        cur += c;
      }
    } else if (c === ",") {
      out.push(cur);
      cur = "";
    } else if (c === '"' && cur === "") {
      inQuotes = true;
    } else {
      cur += c;
    }
  }
  out.push(cur);
  return out;
}

function main() {
  const raw = readFileSync(CSV_PATH, "utf8");
  const lines = raw.split(/\r?\n/).filter((l) => l.trim().length > 0);

  if (lines.length === 0) throw new Error("schools.csv is empty");

  const headers = splitRow(lines[0]);
  const idx = Object.fromEntries(
    WANTED.map((name) => [name, headers.indexOf(name)]),
  ) as Record<WantedColumn, number>;

  for (const name of WANTED) {
    if (idx[name] === -1) throw new Error(`Missing CSV column: ${name}`);
  }

  const cell = (cols: string[], name: WantedColumn) =>
    (cols[idx[name]] ?? "").trim();

  const rows: SchoolServiceRow[] = lines.slice(1).map((line) => {
    const cols = splitRow(line);
    return {
      codInst: cell(cols, "CODINST"),
      codMod: cell(cols, "COD_MOD"),
      codLocal: cell(cols, "CODLOCAL"),
      cenEdu: cell(cols, "CEN_EDU"),
      level: cell(cols, "D_NIV_MOD"),
      address: cell(cols, "DIR_CEN"),
      district: cell(cols, "D_DIST"),
      businessName: cell(cols, "RZSOCIAL"),
    };
  });

  const { schools, stats } = groupSchoolServices(rows);

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(
    OUT_PATH,
    `// AUTO-GENERATED by prisma/scripts/parse-schools.ts — do not edit by hand.\n` +
      `// Regenerate with: pnpm db:parse-schools\n` +
      `// One real school per entry; \`codMods\` lists the merged MINEDU services.\n\n` +
      `export interface SchoolSeed {\n` +
      `  institutionKey: string;\n` +
      `  cenEdu: string;\n` +
      `  district: string;\n` +
      `  address: string;\n` +
      `  businessName: string;\n` +
      `  levels: string[];\n` +
      `  codMods: string[];\n` +
      `}\n\n` +
      `export const SCHOOLS: SchoolSeed[] = [\n` +
      schools.map((s) => `  ${JSON.stringify(s)},`).join("\n") +
      `\n];\n`,
    "utf8",
  );

  console.log(`Wrote ${OUT_PATH}.`);
  console.table(stats);
}

main();
