/**
 * Offline parser — converts `prisma/data/schools.csv` into a typed TS module
 * `prisma/data/schools.generated.ts`. The seed imports the generated module
 * so the CSV is NOT required in production.
 *
 * Run with:  pnpm db:parse-schools
 *
 * Picks the 6 relevant columns (per requirements):
 *   COD_MOD     -> codMod (unique id)
 *   CEN_EDU     -> cenEdu
 *   D_NIV_MOD   -> level
 *   DIR_CEN     -> address
 *   D_DIST      -> district
 *   RZSOCIAL    -> businessName
 *
 * Notes
 * - The source CSV starts with a blank line; the real header is on line 2.
 * - Reads with UTF-8 (file is UTF-8 per `file(1)` output).
 * - Minimal RFC-4180 row parser handles optional quoted fields and embedded commas.
 * - Deduplicates by COD_MOD (last write wins) to ensure the unique constraint
 *   on the generated module.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

const CSV_PATH = resolve("prisma/data/schools.csv");
const OUT_PATH = resolve("prisma/data/schools.generated.ts");

const WANTED = [
  "COD_MOD",
  "CEN_EDU",
  "D_NIV_MOD",
  "DIR_CEN",
  "D_DIST",
  "RZSOCIAL",
] as const;

interface SchoolSeed {
  codMod: string;
  cenEdu: string;
  level: string;
  address: string;
  district: string;
  businessName: string;
}

/** Minimal RFC-4180 row splitter. Handles quoted fields + escaped quotes. */
function splitRow(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (inQuotes) {
      if (c === '"') {
        if (line[i + 1] === '"') {
          cur += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        cur += c;
      }
    } else if (c === ",") {
      out.push(cur);
      cur = "";
    } else if (c === '"' && cur === "") {
      inQuotes = true;
    } else {
      cur += c;
    }
  }
  out.push(cur);
  return out;
}

function main() {
  const raw = readFileSync(CSV_PATH, "utf8");
  const lines = raw.split(/\r?\n/).filter((l) => l.trim().length > 0);

  if (lines.length === 0) throw new Error("schools.csv is empty");

  const headers = splitRow(lines[0]);
  const idx: Record<(typeof WANTED)[number], number> = Object.fromEntries(
    WANTED.map((name) => [name, headers.indexOf(name)]),
  ) as Record<(typeof WANTED)[number], number>;

  // Verify every required column was found.
  for (const name of WANTED) {
    if (idx[name] === -1) throw new Error(`Missing CSV column: ${name}`);
  }

  // Deduplicate by codMod via Map (later occurrence wins, harmless either way).
  const rows = new Map<string, SchoolSeed>();
  let skipped = 0;

  for (let i = 1; i < lines.length; i++) {
    const cols = splitRow(lines[i]);
    const codMod = (cols[idx.COD_MOD] ?? "").trim();
    if (!codMod) {
      skipped++;
      continue;
    }
    rows.set(codMod, {
      codMod,
      cenEdu: (cols[idx.CEN_EDU] ?? "").trim(),
      level: (cols[idx.D_NIV_MOD] ?? "").trim(),
      address: (cols[idx.DIR_CEN] ?? "").trim(),
      district: (cols[idx.D_DIST] ?? "").trim(),
      businessName: (cols[idx.RZSOCIAL] ?? "").trim(),
    });
  }

  const data = Array.from(rows.values());

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(
    OUT_PATH,
    `// AUTO-GENERATED by prisma/scripts/parse-schools.ts — do not edit by hand.\n` +
      `// Regenerate with: pnpm db:parse-schools\n\n` +
      `export interface SchoolSeed {\n` +
      `  codMod: string;\n` +
      `  cenEdu: string;\n` +
      `  level: string;\n` +
      `  address: string;\n` +
      `  district: string;\n` +
      `  businessName: string;\n` +
      `}\n\n` +
      `export const SCHOOLS: SchoolSeed[] = ${JSON.stringify(data, null, 2)};\n`,
    "utf8",
  );

  console.log(
    `Parsed ${data.length} schools from ${lines.length - 1} data rows (skipped ${skipped} without COD_MOD). Wrote ${OUT_PATH}.`,
  );
}

main();
